
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: gmail-username
    password: gmail-password
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.auth: true
    properties.mail.smtp.connectiontimeout: 5000
    properties.mail.smtp.timeout: 5000
    properties.mail.smtp.writetimeout: 5000

  redis:
    url: redis://localhost:6379    # Connection URL, will override host, port and password (user will be ignored)
                                   # Example: redis://user:password@example.com:6379
